export const  ADD_TODOS = 'ADD_TODOS'
export const  LOADING_TRUE = 'LOADING_TRUE'
export const  LOADING_FALSE = 'LOADING_FALSE'
export const  PUSH_TODO = 'PUSH_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const STATUS_TODO = 'STATUS_TODO'
